# Generated by Django 6.0.3 on 2026-04-19 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='exams_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='exams_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_reg_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reg_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registrar_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registrar_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_reg_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='status',
            field=models.CharField(choices=[('pending_exams', 'Pending Exams Office Approval'), ('pending_hod', 'Pending HOD Approval'), ('pending_registrar', 'Pending Registrar Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped')], default='pending_exams', max_length=20),
        ),
    ]
