# Generated by Django 6.0.4 on 2026-04-15 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA_VERIFY', '2FA Verified'), ('SCORE_ENTRY', 'Score Entry'), ('SCORE_SUBMIT', 'Score Submit'), ('SCORE_APPROVE', 'Score Approve'), ('RESULT_RELEASE', 'Result Release'), ('PAYMENT_RECORD', 'Payment Recorded'), ('FEE_OVERRIDE', 'Fee Override'), ('RECEIPT_GENERATE', 'Receipt Generated'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('ROLE_CHANGE', 'Role Changed'), ('ACCOUNT_LOCK', 'Account Locked'), ('ACCOUNT_UNLOCK', 'Account Unlocked'), ('PERMISSION_GRANT', 'Permission Granted'), ('OTP_ISSUE', 'OTP Issued'), ('OTP_USE', 'OTP Used'), ('COURSE_REGISTER', 'Course Registration'), ('CONFIG_CHANGE', 'Config Changed'), ('EXPORT', 'Data Export'), ('OTHER', 'Other')], max_length=30)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='ict_directo_user_id_6e0cfb_idx'), models.Index(fields=['created_at'], name='ict_directo_created_ba7316_idx'), models.Index(fields=['action', 'status'], name='ict_directo_action_26b589_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneralPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('late_course_reg', 'Late Course Registration'), ('score_re_entry', 'Score Re-entry'), ('fee_override', 'Fee Override'), ('result_unlock', 'Result Unlock'), ('bulk_user_import', 'Bulk User Import'), ('role_escalation', 'Role Escalation'), ('other', 'Other')], max_length=30)),
                ('reason', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('otp_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_approved_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['granted_to', 'permission_type', 'is_active'], name='ict_directo_granted_d26191_idx')],
            },
        ),
    ]
