# Generated by Django 6.0.3 on 2026-04-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='dean_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='dean_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_scoresheet_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='exams_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='exams_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_scoresheet_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_scoresheet_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='registrar_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='registrar_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_scoresheet_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Lecturer)'), ('pending_hod', 'Pending HOD Approval'), ('pending_exams', 'Pending Exams Moderation'), ('pending_dean', 'Pending Dean Review'), ('pending_registrar', 'Pending Registrar Publication'), ('published', 'Published'), ('rejected', 'Rejected/Returned')], default='draft', max_length=30),
        ),
    ]
