# Generated by Django 6.0.3 on 2026-04-14 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Student level: 100, 200, 300, 400', max_length=10)),
                ('program', models.CharField(help_text='Program type', max_length=100)),
                ('academic_year', models.CharField(help_text='e.g., 2023/2024', max_length=9)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('examination_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sports_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('development_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', 'level'],
                'unique_together': {('level', 'program', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='OtherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('accommodation', 'Accommodation Fee'), ('feeding', 'Feeding Fee'), ('textbooks', 'Textbooks'), ('project', 'Project Fee'), ('certification', 'Certification'), ('late_registration', 'Late Registration'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online Payment'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check')], default='online', max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_other_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online Payment'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], default='online', max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True, help_text='Description of what the payment covers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='fees_feepay_student_99fef1_idx'), models.Index(fields=['transaction_reference'], name='fees_feepay_transac_8b8071_idx')],
            },
        ),
    ]
