# Generated by Django 6.0.3 on 2026-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='acceptance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='hostel_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
