# Generated by Django 6.0.3 on 2026-04-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_acceptance_fee_feestructure_hostel_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='total_fee',
        ),
    ]
