# Generated by Django 6.0.3 on 2026-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_rename_tuition_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_fee_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tuition fee per credit unit', max_digits=12, null=True),
        ),
    ]
