# Generated by Django 6.0.3 on 2026-04-29 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_feestructure_tuition_fee_per_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this fee item, e.g. 'Tuition Fee', 'Lab Coat Fee'", max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount for this fee item in Naira', max_digits=12)),
                ('category', models.CharField(choices=[('tuition', 'Tuition & Academic'), ('registration', 'Registration'), ('examination', 'Examination'), ('development', 'Development Levy'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('medical', 'Medical / Insurance'), ('sports', 'Sports'), ('hostel', 'Hostel / Accommodation'), ('ict', 'ICT / Technology'), ('acceptance', 'Acceptance Fee'), ('other', 'Other Charges')], default='other', help_text='Category for grouping in reports', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description shown to students')),
                ('academic_year', models.CharField(default='2025/2026', help_text='Academic year this fee applies to', max_length=9)),
                ('is_active', models.BooleanField(default=True, help_text='Only active items are shown to students and counted in totals')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory items are required for all students')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this item appears in the fee breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Bursary staff who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Item',
                'verbose_name_plural': 'Fee Items',
                'ordering': ['display_order', 'category', 'name'],
            },
        ),
    ]
