# Generated by Django 6.0.3 on 2026-04-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('academic_year', models.CharField(default='2024/2025', max_length=9)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Registration Started'), ('in_progress', 'Details In Progress'), ('submitted', 'Application Submitted'), ('paid', 'Application Fee Paid'), ('under_review', 'Under Review'), ('admitted', 'Admitted'), ('rejected', 'Not Admitted')], default='started', max_length=20)),
                ('is_fee_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('first_choice_program', models.CharField(blank=True, max_length=100)),
                ('second_choice_program', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('nok_name', models.CharField(blank=True, max_length=100)),
                ('nok_phone', models.CharField(blank=True, max_length=20)),
                ('nok_address', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='admissions.applicationrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Photograph'), ('olevel_result', 'O-Level Statement of Result'), ('jamb_result', 'JAMB Result Slip'), ('indigene_cert', 'Indigene Certificate'), ('birth_cert', 'Birth Certificate / Declaration of Age'), ('other', 'Other Supporting Document')], max_length=20)),
                ('file', models.FileField(upload_to='admission_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicationrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_reg_number', models.CharField(blank=True, max_length=20)),
                ('jamb_score', models.PositiveIntegerField(blank=True, null=True)),
                ('sitting_count', models.PositiveIntegerField(default=1)),
                ('olevel_results', models.JSONField(blank=True, default=dict)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='admissions.applicationrecord')),
            ],
        ),
    ]
