# Generated by Django 6.0.3 on 2026-04-22 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rebuild_admissions_for_nursing_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiondocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='applicantprofile',
            options={'verbose_name': 'Applicant Profile', 'verbose_name_plural': 'Applicant Profiles'},
        ),
        migrations.AlterModelOptions(
            name='applicationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='olevel_results',
            field=models.JSONField(blank=True, default=dict, help_text='Store as {Subject: Grade}'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='olevel_sitting_count',
            field=models.PositiveIntegerField(choices=[(1, 'First Sitting'), (2, 'Second Sitting')], default=1),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='nok_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Next of Kin Name'),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=9),
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['user', 'status'], name='admissions__user_id_60fa36_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['application_number'], name='admissions__applica_895b47_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['academic_year'], name='admissions__academi_d7719e_idx'),
        ),
    ]
