# Generated by Django 6.0.3 on 2026-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissiondocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecord',
            name='application_type',
            field=models.CharField(choices=[('utme', 'UTME (Undergraduate)'), ('de', 'Direct Entry (DE)'), ('sandwich', 'Sandwich Programme'), ('diploma', 'Diploma / Certificate')], default='utme', max_length=20),
        ),
    ]
