# Generated by Django 6.0.3 on 2026-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_locked_until_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('dean', 'Dean of Faculty'), ('bursary', 'Bursary Officer'), ('registrar', 'Registrar'), ('exams_officer', 'Exams & Records Officer'), ('hostel_admin', 'Hostel Administrator'), ('ict_director', 'ICT Director'), ('vice_chancellor', 'Vice Chancellor')], default='student', help_text='User role in the system', max_length=20),
        ),
    ]
