# Generated by Django 6.0.3 on 2026-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('applicant', 'Applicant'), ('lecturer', 'Lecturer'), ('practical_master', 'Practical Master'), ('hod', 'Head of Department'), ('hod_coordinator', 'HOD Coordinator'), ('dean_students_affairs', 'Dean of Students Affairs'), ('deputy_dean_students_affairs', 'Deputy Dean of Students Affairs'), ('academic_secretary', 'Academic Secretary'), ('provost', 'Provost'), ('registrar', 'Registrar'), ('deputy_registrar', 'Deputy Registrar'), ('exams_officer', 'Exams & Records Officer'), ('admin_officer', 'Admin Officer'), ('bursary', 'Bursar'), ('liaison_officer', 'Liaison Officer'), ('hostel_admin', 'Hostel Administrator'), ('ict_director', 'ICT Director'), ('director', 'Director')], default='student', help_text='User role in the system', max_length=30),
        ),
    ]
