# Generated by Django 6.0.3 on 2026-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if student has completed biodata registration on portal'),
        ),
    ]
