# Generated by Django 6.0.3 on 2026-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_profile_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['department_code', 'matriculation_number'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='program',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=9),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department_code',
            field=models.CharField(choices=[('PHT', 'Public Health Technology'), ('HIMT', 'Health Information Management Technology'), ('CHEW', 'Community Health Extension Workers'), ('PT', 'Pharmacy Technician'), ('MLT', 'Medical Laboratory Technician')], default='PHT', help_text='Department code (PHT, HIMT, CHEW, PT, MLT)', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsor_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsor_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='current_rank',
            field=models.CharField(choices=[('graduate_assistant', 'Graduate Assistant'), ('assistant_lecturer', 'Assistant Lecturer'), ('lecturer_ii', 'Lecturer II'), ('lecturer_i', 'Lecturer I'), ('senior_lecturer', 'Senior Lecturer'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('administrative', 'Administrative Staff')], default='administrative', help_text='Current rank/position', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_of_current_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_of_first_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(help_text='Full department name', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(default='100', help_text='e.g., 100, 200', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='local_government',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matriculation_number',
            field=models.CharField(help_text='Official matric number e.g. YCHST/2025/2026/PHT/001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='True once student submits complete biodata'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Matric number for students.', max_length=50, unique=True, verbose_name='username'),
        ),
    ]
