# Generated by Django 6.0.3 on 2026-04-29 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025/2026', help_text='Academic year for this clearance cycle', max_length=9)),
                ('status', models.CharField(choices=[('pending_acceptance', 'Awaiting Acceptance Fee'), ('pending_documents', 'Awaiting Document Upload'), ('pending_approval', 'Awaiting Registrar Approval'), ('approved', 'Clearance Approved'), ('rejected', 'Clearance Rejected')], default='pending_acceptance', help_text='Current stage in the clearance pipeline', max_length=25)),
                ('acceptance_fee_paid', models.BooleanField(default=False)),
                ('acceptance_fee_amount', models.DecimalField(decimal_places=2, default=25000.0, help_text='Amount charged for acceptance fee (configurable by Bursary)', max_digits=12)),
                ('acceptance_payment_ref', models.CharField(blank=True, help_text='Payment reference for acceptance fee', max_length=100)),
                ('acceptance_paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('matric_generated', models.BooleanField(default=False, help_text='True once matriculation number has been assigned')),
                ('matric_generated_at', models.DateTimeField(blank=True, null=True)),
                ('matric_locked', models.BooleanField(default=False, help_text='Once True, matric cannot be regenerated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Registrar who approved this clearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Clearance',
                'verbose_name_plural': 'Student Clearances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clearance.studentclearance')),
            ],
            options={
                'verbose_name': 'Clearance Status History',
                'verbose_name_plural': 'Clearance Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('waec_neco', 'WAEC/NECO Result'), ('birth_certificate', 'Birth Certificate'), ('passport_photo', 'Passport Photograph'), ('acceptance_letter', 'Acceptance Letter'), ('lga_certificate', 'LGA Identification'), ('medical_report', 'Medical Report'), ('other', 'Other Supporting Document')], help_text='Type of clearance document', max_length=25)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='clearance_docs/%Y/')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, help_text='Reason for document rejection')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clearance_docs', to=settings.AUTH_USER_MODEL)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clearance.studentclearance')),
            ],
            options={
                'verbose_name': 'Clearance Document',
                'verbose_name_plural': 'Clearance Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.AddIndex(
            model_name='studentclearance',
            index=models.Index(fields=['student', 'status'], name='clearance_s_student_9c423c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclearance',
            index=models.Index(fields=['academic_year', 'status'], name='clearance_s_academi_542ecd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clearancedocument',
            unique_together={('clearance', 'document_type')},
        ),
    ]
