# Generated by Django 6.0.3 on 2026-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('all', 'All Users'), ('student', 'Students'), ('staff', 'Staff'), ('hod', 'HODs'), ('dean', 'Deans'), ('exams_officer', 'Exams Officers'), ('registrar', 'Registrar Office'), ('ict_director', 'ICT Director'), ('bursary', 'Bursary Office')], max_length=20, null=True),
        ),
    ]
